# Generated by Django 3.0.8 on 2020-07-10 05:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ваше ФИО')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +79998887766', regex='^\\+?7?\\d{10}$')], verbose_name='Ваш номер телефона')),
                ('text', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Ваш отзыв')),
                ('add_datetime', models.DateTimeField(auto_now=True, verbose_name='время добавления отзыва')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='Путь до фотки')),
                ('add_datetime', models.DateTimeField(auto_now=True, verbose_name='время добавления фото')),
                ('text', models.TextField(blank=True, max_length=256, null=True)),
                ('category', models.TextField(blank=True, choices=[('COMMON', 'ОБЩИЕ ФОТО'), ('STAFF', 'ФОТО ПЕРСОНАЛА')], max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='наименование категории услуг')),
                ('desc', models.TextField(blank=True, max_length=1200, null=True, verbose_name='зачем нужна эта категория услуг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/services', verbose_name='путь до фотки')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='наименование иконки')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/slider', verbose_name='Путь до фотки')),
                ('text', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='наименование услуги')),
                ('desc', models.TextField(blank=True, max_length=1200, null=True, verbose_name='описание')),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.ServiceCategory')),
            ],
        ),
    ]
